/**
 * Central Color Palette — AUTO-GENERATED
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Edit `channels/<channel>/channel-assets/design-system.json` instead,
 * then run `npm run sync-palette` to regenerate.
 *
 * Source: design-system "dusty-editorial" v3
 * Generated: 2026-03-27T21:58:30.168Z
 *
 * Architecture:
 *   design-system.json  → SINGLE SOURCE OF TRUTH (edit here)
 *   palette.ts (this)   → generated, imported by all Remotion components
 *   vibes/theme-context  → imports from palette.ts
 *   templates/*          → imports from palette.ts
 */

// ─── Base Colors ──────────────────────────────────────────────

export const BG = "#2A2A32";
export const TEXT = "#F0EDE8";
export const ACCENT_PINK = "#E88CA5";
export const ACCENT_BLUE = "#7BA7C9";
export const SAGE = "#8A9A7A";
export const POSITIVE = "#5BBF8C";
export const NEGATIVE = "#E06070";

// ─── Text Variants ────────────────────────────────────────────

export const TEXT_MUTED = "rgba(240, 237, 232, 0.55)";
export const TEXT_SECONDARY = "rgba(240, 237, 232, 0.7)";
export const TEXT_FAINT = "rgba(240, 237, 232, 0.4)";

// ─── Surface / Container ──────────────────────────────────────

export const SURFACE = "rgba(255, 255, 255, 0.06)";
export const SURFACE_HOVER = "rgba(255, 255, 255, 0.08)";
export const SURFACE_BORDER = "rgba(255, 255, 255, 0.1)";
export const SURFACE_BORDER_STRONG = "rgba(240, 237, 232, 0.12)";

// ─── Chart-Specific ───────────────────────────────────────────

export const TRACK = "rgba(240, 237, 232, 0.06)";
export const GRID = "rgba(240, 237, 232, 0.15)";
export const CARD_BG = "rgba(42, 42, 50, 0.92)";
export const CARD_BORDER = "rgba(240, 237, 232, 0.08)";

// ─── Data Palette ─────────────────────────────────────────────

export const DATA_PALETTE = [
  ACCENT_PINK,
  ACCENT_BLUE,
  POSITIVE,
  NEGATIVE,
  SAGE,
  "#7EC8E3",
  "#F4A261",
  "#9B59B6",
] as const;

// ─── Convenience Object ───────────────────────────────────────

export const PALETTE = {
  bg: BG,
  text: TEXT,
  textMuted: TEXT_MUTED,
  textSecondary: TEXT_SECONDARY,
  textFaint: TEXT_FAINT,
  accentPink: ACCENT_PINK,
  accentBlue: ACCENT_BLUE,
  sage: SAGE,
  positive: POSITIVE,
  negative: NEGATIVE,
  surface: SURFACE,
  surfaceHover: SURFACE_HOVER,
  surfaceBorder: SURFACE_BORDER,
  surfaceBorderStrong: SURFACE_BORDER_STRONG,
  track: TRACK,
  grid: GRID,
  cardBg: CARD_BG,
  cardBorder: CARD_BORDER,
  dataPalette: DATA_PALETTE,
} as const;

export type Palette = typeof PALETTE;
