/**
 * AI Image Generation Router Script
 *
 * Routes to the correct image generation provider based on channel-config.json
 * or CLI flag override.
 *
 * Usage: npm run generate-image <project-slug> <prompt> [--provider gemini|dalle] [--format short|long]
 *
 * Writes: projects/<slug>/production/visuals/
 */

import "dotenv/config";
import * as fs from "node:fs";
import * as path from "node:path";
import { ensureProjectDir, appendAssetLog, loadChannelConfig } from "../utils/project.js";

type Provider = "gemini" | "dalle";

async function main() {
  const args = process.argv.slice(2);
  const slug = args[0];

  // Parse --provider flag
  const providerFlagIndex = args.indexOf("--provider");
  let providerOverride: Provider | null = null;
  if (providerFlagIndex !== -1 && args[providerFlagIndex + 1]) {
    providerOverride = args[providerFlagIndex + 1] as Provider;
  }

  // Parse --format flag
  const formatFlagIndex = args.indexOf("--format");
  let format: "long" | "short" = "long";
  if (formatFlagIndex !== -1 && args[formatFlagIndex + 1]) {
    format = args[formatFlagIndex + 1] as "long" | "short";
  }

  // Collect prompt (everything except slug and flags)
  const flagIndices = new Set<number>();
  if (providerFlagIndex !== -1) {
    flagIndices.add(providerFlagIndex);
    flagIndices.add(providerFlagIndex + 1);
  }
  if (formatFlagIndex !== -1) {
    flagIndices.add(formatFlagIndex);
    flagIndices.add(formatFlagIndex + 1);
  }

  const prompt = args
    .slice(1)
    .filter((_, i) => !flagIndices.has(i + 1))
    .join(" ");

  if (!slug || !prompt) {
    console.error('Usage: npm run generate-image <project-slug> "image description" [--provider gemini|dalle] [--format short|long]');
    process.exit(1);
  }

  // Determine provider from channel config or override
  let provider: Provider = "gemini";
  try {
    const channelConfig = loadChannelConfig();
    const configProvider = (channelConfig.visuals as Record<string, unknown>).imageProvider as string;
    if (configProvider === "gemini" || configProvider === "dalle") {
      provider = configProvider;
    }
  } catch {
    // No channel config, default to gemini
  }
  if (providerOverride) {
    provider = providerOverride;
  }

  console.log(`Using image provider: ${provider}`);

  if (provider === "gemini") {
    await generateWithGemini(slug, prompt, format);
  } else {
    await generateWithDalle(slug, prompt, format);
  }
}

async function generateWithGemini(slug: string, prompt: string, format: "long" | "short") {
  const apiKey = process.env.GOOGLE_AI_API_KEY;
  if (!apiKey) {
    console.error("Missing GOOGLE_AI_API_KEY in .env");
    process.exit(1);
  }

  const visualsDir = ensureProjectDir(slug, "production/visuals");
  const aspectRatio = format === "short" ? "9:16" : "16:9";

  console.log(`Generating image with Gemini (${aspectRatio}): "${prompt}"...`);

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${apiKey}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `Generate a high-quality image: ${prompt}. Style: photorealistic, cinematic lighting, ultra detailed.`,
              },
            ],
          },
        ],
        generationConfig: {
          responseModalities: ["TEXT", "IMAGE"],
        },
      }),
    }
  );

  if (!response.ok) {
    console.error(`Gemini API error: ${response.status}`);
    const body = await response.text();
    console.error(body);
    process.exit(1);
  }

  const data = (await response.json()) as {
    candidates: Array<{
      content: {
        parts: Array<{
          text?: string;
          inlineData?: { mimeType: string; data: string };
        }>;
      };
    }>;
  };

  const candidate = data.candidates?.[0];
  if (!candidate) {
    console.error("No candidates returned from Gemini API");
    process.exit(1);
  }

  const imagePart = candidate.content.parts.find((p) => p.inlineData);
  if (!imagePart?.inlineData) {
    console.error("No image generated by Gemini.");
    const textPart = candidate.content.parts.find((p) => p.text);
    if (textPart) console.error(textPart.text);
    process.exit(1);
  }

  const buffer = Buffer.from(imagePart.inlineData.data, "base64");
  const ext = imagePart.inlineData.mimeType.includes("png") ? "png" : "jpg";

  const sanitizedPrompt = prompt
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);

  const filename = `gemini-${Date.now()}-${sanitizedPrompt}.${ext}`;
  const filePath = path.join(visualsDir, filename);
  fs.writeFileSync(filePath, buffer);

  console.log(`Image saved: ${filePath}`);

  const textPart = candidate.content.parts.find((p) => p.text);
  if (textPart?.text) {
    console.log(`Gemini notes: ${textPart.text}`);
  }

  appendAssetLog(slug, {
    type: "ai-image",
    source: "Gemini Imagen",
    file: `visuals/${filename}`,
    license: "Generated",
    query: prompt,
  });
}

async function generateWithDalle(slug: string, prompt: string, format: "long" | "short") {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.error("Missing OPENAI_API_KEY in .env");
    process.exit(1);
  }

  const visualsDir = ensureProjectDir(slug, "production/visuals");
  const size = format === "short" ? "1024x1792" : "1792x1024";

  console.log(`Generating image with DALL-E (${size}): "${prompt}"...`);

  const response = await fetch("https://api.openai.com/v1/images/generations", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "dall-e-3",
      prompt,
      n: 1,
      size,
      quality: "standard",
      response_format: "b64_json",
    }),
  });

  if (!response.ok) {
    console.error(`OpenAI API error: ${response.status}`);
    const body = await response.text();
    console.error(body);
    process.exit(1);
  }

  const data = (await response.json()) as {
    data: Array<{ b64_json: string; revised_prompt: string }>;
  };

  const image = data.data[0];
  const buffer = Buffer.from(image.b64_json, "base64");

  const sanitizedPrompt = prompt
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);

  const filename = `dalle-${Date.now()}-${sanitizedPrompt}.png`;
  const filePath = path.join(visualsDir, filename);
  fs.writeFileSync(filePath, buffer);

  console.log(`Image saved: ${filePath}`);
  console.log(`Revised prompt: ${image.revised_prompt}`);

  appendAssetLog(slug, {
    type: "ai-image",
    source: "DALL-E 3",
    file: `visuals/${filename}`,
    license: "Generated",
    query: prompt,
  });
}

main().catch((err) => {
  console.error("Image generation failed:", err);
  process.exit(1);
});
