/**
 * Sync Palette Script
 *
 * Reads `channels/<channel>/channel-assets/design-system.json` (the SINGLE SOURCE OF TRUTH
 * for brand colors) and generates `src/remotion/palette.ts`.
 *
 * Also syncs `channel-config.json` brand.colors to match design-system.json.
 *
 * Usage:
 *   npm run sync-palette [--channel <slug>]
 *
 * When to run:
 *   - After editing design-system.json
 *   - Before rendering (automated via pre-render hook)
 */

import * as fs from "node:fs";
import * as path from "node:path";

const CHANNELS_DIR = path.resolve("channels");
const PALETTE_OUTPUT = path.resolve("src/remotion/palette.ts");

interface DesignSystemColors {
  bgTop: string;
  bgBottom: string;
  accent1: string;
  accent2: string;
  text: string;
  textMuted: string;
  positive: string;
  negative: string;
  surface: string;
  border: string;
  grid: string;
}

interface DesignSystem {
  name: string;
  version: number;
  colors?: DesignSystemColors;
  tokens?: { colors?: DesignSystemColors };
}

function unwrapColors(ds: DesignSystem): DesignSystemColors {
  const c = ds.tokens?.colors ?? ds.colors;
  if (!c) {
    console.error("❌ design-system.json missing colors (expected at .tokens.colors or .colors)");
    process.exit(1);
  }
  return c;
}

// ─── Resolve channel ──────────────────────────────────────────

function resolveChannel(): string {
  const args = process.argv.slice(2);
  const channelIdx = args.indexOf("--channel");
  if (channelIdx !== -1 && args[channelIdx + 1]) {
    return args[channelIdx + 1];
  }
  // Auto-detect first channel
  const entries = fs.readdirSync(CHANNELS_DIR, { withFileTypes: true });
  const first = entries.find((e) => e.isDirectory() && !e.name.startsWith("."));
  if (!first) {
    console.error("❌ No channels found in channels/");
    process.exit(1);
  }
  return first.name;
}

// ─── Parse rgba to extract base RGB ──────────────────────────

function rgbaComponents(rgba: string): { r: number; g: number; b: number; a: number } | null {
  const match = rgba.match(/rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+))?\s*\)/);
  if (!match) return null;
  return {
    r: parseInt(match[1]),
    g: parseInt(match[2]),
    b: parseInt(match[3]),
    a: match[4] ? parseFloat(match[4]) : 1,
  };
}

function hexToRgb(hex: string): { r: number; g: number; b: number } {
  const clean = hex.replace("#", "");
  return {
    r: parseInt(clean.substring(0, 2), 16),
    g: parseInt(clean.substring(2, 4), 16),
    b: parseInt(clean.substring(4, 6), 16),
  };
}

function rgbaStr(r: number, g: number, b: number, a: number): string {
  return `rgba(${r}, ${g}, ${b}, ${a})`;
}

// ─── Generate palette.ts ──────────────────────────────────────

function generatePalette(ds: DesignSystem): string {
  const c = unwrapColors(ds);
  const textRgb = hexToRgb(c.text);
  const tr = textRgb.r, tg = textRgb.g, tb = textRgb.b;

  // Extract textMuted opacity from design-system value
  const mutedParsed = rgbaComponents(c.textMuted);
  const mutedOpacity = mutedParsed?.a ?? 0.6;

  // Derive text variants from the text base color
  const textMuted = rgbaStr(tr, tg, tb, 0.55);
  const textSecondary = rgbaStr(tr, tg, tb, 0.7);
  const textFaint = rgbaStr(tr, tg, tb, 0.4);

  // Surface variants
  const surface = c.surface;
  const surfaceHover = "#313140";
  const surfaceBorder = rgbaStr(tr, tg, tb, 0.07);
  const surfaceBorderStrong = c.border || rgbaStr(tr, tg, tb, 0.12);

  // Chart-specific
  const track = rgbaStr(tr, tg, tb, 0.06);
  const grid = c.grid;
  const cardBg = c.surface;
  const cardBorder = rgbaStr(tr, tg, tb, 0.10);
  const axis = rgbaStr(tr, tg, tb, 0.35);

  const now = new Date().toISOString();

  return `/**
 * Central Color Palette — AUTO-GENERATED
 *
 * DO NOT EDIT THIS FILE MANUALLY.
 * Edit \`channels/<channel>/channel-assets/design-system.json\` instead,
 * then run \`npm run sync-palette\` to regenerate.
 *
 * Source: design-system "${ds.name}" v${ds.version}
 * Generated: ${now}
 *
 * Architecture:
 *   design-system.json  → SINGLE SOURCE OF TRUTH (edit here)
 *   palette.ts (this)   → generated, imported by all Remotion components
 *   vibes/theme-context  → imports from palette.ts
 *   templates/*          → imports from palette.ts
 */

// ─── Base Colors ──────────────────────────────────────────────

export const BG = "${c.bgTop}";
export const TEXT = "${c.text}";
export const ACCENT_PINK = "${c.accent1}";
export const ACCENT_BLUE = "${c.accent2}";
export const POSITIVE = "${c.positive}";
export const NEGATIVE = "${c.negative}";

// ─── Structural ───────────────────────────────────────────────

export const AXIS = "${axis}";   // axis labels, tick marks
export const SAGE = AXIS;          // structural axis color only — not a brand color

// ─── Text Variants ────────────────────────────────────────────

export const TEXT_MUTED = "${textMuted}";
export const TEXT_SECONDARY = "${textSecondary}";
export const TEXT_FAINT = "${textFaint}";

// ─── Surface / Container ──────────────────────────────────────

export const SURFACE = "${surface}";
export const SURFACE_HOVER = "${surfaceHover}";
export const SURFACE_BORDER = "${surfaceBorder}";
export const SURFACE_BORDER_STRONG = "${surfaceBorderStrong}";

// ─── Chart-Specific ───────────────────────────────────────────

export const TRACK = "${track}";
export const GRID = "${grid}";
export const CARD_BG = "${cardBg}";
export const CARD_BORDER = "${cardBorder}";

// ─── Data Palette ─────────────────────────────────────────────

export const DATA_PALETTE = [
  ACCENT_PINK,
  ACCENT_BLUE,
  POSITIVE,
  NEGATIVE,
  "#7EC8E3",
  "#F4A261",
  "#C084FC",
  "#FB923C",
] as const;

// ─── Convenience Object ───────────────────────────────────────

export const PALETTE = {
  bg: BG,
  text: TEXT,
  textMuted: TEXT_MUTED,
  textSecondary: TEXT_SECONDARY,
  textFaint: TEXT_FAINT,
  accentPink: ACCENT_PINK,
  accentBlue: ACCENT_BLUE,
  axis: AXIS,
  sage: SAGE,
  positive: POSITIVE,
  negative: NEGATIVE,
  surface: SURFACE,
  surfaceHover: SURFACE_HOVER,
  surfaceBorder: SURFACE_BORDER,
  surfaceBorderStrong: SURFACE_BORDER_STRONG,
  track: TRACK,
  grid: GRID,
  cardBg: CARD_BG,
  cardBorder: CARD_BORDER,
  dataPalette: DATA_PALETTE,
} as const;

export type Palette = typeof PALETTE;
`;
}

// ─── Sync channel-config.json ─────────────────────────────────

function syncChannelConfig(channelSlug: string, ds: DesignSystem): void {
  const configPath = path.join(CHANNELS_DIR, channelSlug, "channel-config.json");
  if (!fs.existsSync(configPath)) {
    console.warn(`⚠️  channel-config.json not found at ${configPath}, skipping sync`);
    return;
  }

  const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
  const c = unwrapColors(ds);

  // Sync brand.colors
  if (config.brand?.colors) {
    config.brand.colors = {
      bgTop: c.bgTop,
      bgBottom: c.bgBottom,
      accent1: c.accent1,
      accent2: c.accent2,
      text: c.text,
      textMuted: c.textMuted,
      positive: c.positive,
      negative: c.negative,
      surface: c.surface,
      border: c.border,
      grid: c.grid,
    };
  }

  // Sync visuals colors
  if (config.visuals) {
    config.visuals.brandColor = c.accent1;
    config.visuals.accentColor = c.accent2;
    config.visuals.backgroundColor = c.bgTop;
    config.visuals.textColor = c.text;
  }

  fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n", "utf-8");
  console.log(`✅ Synced channel-config.json`);
}

// ─── Main ─────────────────────────────────────────────────────

function main(): void {
  const channelSlug = resolveChannel();
  const dsPath = path.join(CHANNELS_DIR, channelSlug, "channel-assets", "design-system.json");

  if (!fs.existsSync(dsPath)) {
    console.error(`❌ design-system.json not found at ${dsPath}`);
    process.exit(1);
  }

  const ds: DesignSystem = JSON.parse(fs.readFileSync(dsPath, "utf-8"));
  console.log(`📎 Reading design-system "${ds.name}" v${ds.version} from ${channelSlug}`);

  // Generate palette.ts
  const paletteContent = generatePalette(ds);
  fs.writeFileSync(PALETTE_OUTPUT, paletteContent, "utf-8");
  console.log(`✅ Generated ${path.relative(process.cwd(), PALETTE_OUTPUT)}`);

  // Sync channel-config.json
  syncChannelConfig(channelSlug, ds);

  console.log(`\n🎨 Palette sync complete. All colors sourced from design-system.json.`);
}

main();
