/**
 * Publishing model of a layout-2 project.
 *
 *   publishing/metadata.json     written by hand/model: title, description body, tags, category, visibility
 *   publishing/description.txt   generated by npm run metadata (description with chapters, for copy-paste)
 *   publishing/tags.txt          generated by npm run metadata
 *   publishing/upload-log.md     appended by npm run upload
 *   production/output/final.render.json  written by npm run render: hash of the render input that produced final.mp4
 *
 * Chapter timestamps are never typed: they are derived from production/timeline.json and the
 * section titles of script/order.json. The description holds a `{{chapters}}` line where they go.
 */

import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { z } from "zod";
import { loadProjectConfig } from "../utils/project.js";
import { END_PADDING_SEC, START_PADDING_SEC } from "../remotion/timing.js";
import { paths, type Timeline } from "./v2.js";

const defaults = JSON.parse(fs.readFileSync(path.resolve("templates/pipeline-defaults.json"), "utf8")).youtube as {
  maxTagsTotalChars: number;
  targetTagChars: number;
  maxSingleTagChars: number;
  forbiddenTagChars: string[];
};

// ─── Schema ─────────────────────────────────────────────────────────

/** YouTube Data API category ids. */
export const CATEGORIES = {
  Education: "27",
  "Science & Technology": "28",
  Entertainment: "24",
  "News & Politics": "25",
  "People & Blogs": "22",
  "Howto & Style": "26",
} as const;

export const CHAPTERS_TOKEN = "{{chapters}}";

export const metadataSchema = z
  .object({
    title: z.string().min(1).max(100),
    /** Description body. Long videos put `{{chapters}}` on its own line where the chapter list goes. */
    description: z.string().min(1),
    tags: z.array(z.string()).min(1),
    category: z.enum(Object.keys(CATEGORIES) as [keyof typeof CATEGORIES]),
    visibility: z.enum(["private", "unlisted", "public"]).default("private"),
    /** ISO 8601 with offset. YouTube requires visibility private for a scheduled video. */
    scheduledAt: z.string().datetime({ offset: true }).optional(),
  })
  .strict()
  .refine((m) => !m.scheduledAt || m.visibility === "private", { message: "scheduledAt requires visibility private" });
export type Metadata = z.infer<typeof metadataSchema>;

export function publishPaths(slug: string) {
  const root = paths(slug).root;
  const pub = path.join(root, "publishing");
  const out = path.join(root, "production", "output");
  return {
    metadata: path.join(pub, "metadata.json"),
    description: path.join(pub, "description.txt"),
    tags: path.join(pub, "tags.txt"),
    uploadLog: path.join(pub, "upload-log.md"),
    video: path.join(out, "final.mp4"),
    renderStamp: path.join(out, "final.render.json"),
    thumbnailDir: pub,
  };
}

// ─── Tags ───────────────────────────────────────────────────────────

/**
 * Length of the tag list as the YouTube Data API counts it (snippet.tags): commas between
 * tags count, and a tag containing a space counts as if wrapped in quotes (+2).
 */
export function tagChars(tags: string[]): number {
  if (tags.length === 0) return 0;
  return tags.reduce((n, t) => n + t.length + (t.includes(" ") ? 2 : 0), 0) + (tags.length - 1);
}

export function checkTags(tags: string[]): { errors: string[]; warnings: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];
  const seen = new Set<string>();
  for (const t of tags) {
    if (t !== t.trim() || !t) errors.push(`tag "${t}": empty or has surrounding spaces`);
    if (t.length > defaults.maxSingleTagChars) errors.push(`tag "${t}": longer than ${defaults.maxSingleTagChars}`);
    const bad = defaults.forbiddenTagChars.filter((c) => t.includes(c));
    if (bad.length) errors.push(`tag "${t}": forbidden character(s) ${bad.join(" ")}`);
    if (t.includes(",")) errors.push(`tag "${t}": contains a comma`);
    if (seen.has(t.toLowerCase())) errors.push(`tag "${t}": duplicate`);
    seen.add(t.toLowerCase());
  }
  const n = tagChars(tags);
  if (n > defaults.maxTagsTotalChars) errors.push(`tags total ${n} chars, limit ${defaults.maxTagsTotalChars} (API count: commas + quotes around multi-word tags)`);
  else if (n > defaults.targetTagChars) warnings.push(`tags total ${n} chars, above the ${defaults.targetTagChars} target`);
  return { errors, warnings };
}

// ─── Chapters ───────────────────────────────────────────────────────

export interface Chapter {
  title: string;
  /** Seconds from the start of the rendered video. */
  start: number;
}

const stamp = (sec: number) => {
  const s = Math.floor(sec);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const ss = String(s % 60).padStart(2, "0");
  return h ? `${h}:${String(m).padStart(2, "0")}:${ss}` : `${m}:${ss}`;
};

/**
 * One chapter per section of order.json, starting where its first scene starts in the rendered
 * video (content time + START_PADDING_SEC). The first chapter is pinned to 0:00 as YouTube requires.
 */
export function chaptersFromTimeline(timeline: Timeline): Chapter[] {
  const chapters: Chapter[] = [];
  for (const s of timeline.scenes) {
    if (chapters.at(-1)?.title === s.section) continue;
    chapters.push({ title: s.section, start: chapters.length === 0 ? 0 : s.startTime + START_PADDING_SEC });
  }
  return chapters;
}

/** YouTube shows chapters only if there are at least 3, the first at 0:00, each at least 10 seconds long. */
export function checkChapters(chapters: Chapter[], videoEndSec: number): string[] {
  const errors: string[] = [];
  if (chapters.length < 3) errors.push(`${chapters.length} section(s); YouTube chapters need at least 3`);
  chapters.forEach((c, i) => {
    const end = chapters[i + 1]?.start ?? videoEndSec;
    // Timestamps are floored to whole seconds, so measure what the viewer sees.
    const len = Math.floor(end) - Math.floor(c.start);
    if (len < 10) errors.push(`chapter "${c.title}" is ${len}s at ${stamp(c.start)}; YouTube chapters need at least 10s`);
  });
  return errors;
}

export const chapterLines = (chapters: Chapter[]) => chapters.map((c) => `${stamp(c.start)} ${c.title}`).join("\n");

// ─── Build ──────────────────────────────────────────────────────────

export interface BuiltMetadata {
  metadata: Metadata;
  description: string;
  chapters: Chapter[];
  errors: string[];
  warnings: string[];
}

function loadTimeline(slug: string): Timeline | undefined {
  const file = paths(slug).timeline;
  return fs.existsSync(file) ? (JSON.parse(fs.readFileSync(file, "utf8")) as Timeline) : undefined;
}

/** Validates publishing/metadata.json and assembles the final description. Pure read. */
export function buildMetadata(slug: string): BuiltMetadata {
  const file = publishPaths(slug).metadata;
  if (!fs.existsSync(file)) throw new Error(`publishing/metadata.json missing`);
  const metadata = metadataSchema.parse(JSON.parse(fs.readFileSync(file, "utf8")));
  const format = (loadProjectConfig(slug) as any).metadata?.format ?? "long";
  const errors: string[] = [];
  const warnings: string[] = [];

  const tags = checkTags(metadata.tags);
  errors.push(...tags.errors);
  warnings.push(...tags.warnings);

  const tokenLines = metadata.description.split("\n").filter((l) => l.includes(CHAPTERS_TOKEN));
  let chapters: Chapter[] = [];
  let description = metadata.description;
  if (format === "short") {
    if (tokenLines.length) errors.push(`${CHAPTERS_TOKEN} in a short; shorts have no chapters`);
  } else if (tokenLines.length !== 1 || tokenLines[0].trim() !== CHAPTERS_TOKEN) {
    errors.push(`description needs exactly one line that is only ${CHAPTERS_TOKEN}`);
  } else {
    const timeline = loadTimeline(slug);
    if (!timeline) errors.push(`production/timeline.json missing (npm run assemble -- ${slug})`);
    else {
      chapters = chaptersFromTimeline(timeline);
      errors.push(...checkChapters(chapters, START_PADDING_SEC + timeline.totalDuration + END_PADDING_SEC));
      description = description.replace(CHAPTERS_TOKEN, chapterLines(chapters));
    }
  }
  if (description.length > 5000) errors.push(`description is ${description.length} chars, YouTube limit 5000`);
  if (/[<>]/.test(description) || /[<>]/.test(metadata.title)) errors.push(`title/description contain < or >, which YouTube rejects`);

  return { metadata, description, chapters, errors, warnings };
}

/** The videos.insert / videos.update resource. Tags go as a real array. */
export function videoResource(slug: string, built: BuiltMetadata) {
  const language = (loadProjectConfig(slug) as any).metadata?.language ?? "en";
  const { metadata } = built;
  return {
    snippet: {
      title: metadata.title,
      description: built.description,
      tags: metadata.tags,
      categoryId: CATEGORIES[metadata.category],
      defaultLanguage: language,
      defaultAudioLanguage: language,
    },
    status: {
      privacyStatus: metadata.visibility,
      publishAt: metadata.scheduledAt,
      selfDeclaredMadeForKids: false,
    },
  };
}

// ─── Render stamp ───────────────────────────────────────────────────

export const sha256 = (data: Buffer) => createHash("sha256").update(data).digest("hex");
const sha = (file: string) => sha256(fs.readFileSync(file));

/** Final render size as a multiple of the composition (templates/pipeline-defaults.json rendering.uploadScale). */
export function uploadScale(): number {
  return JSON.parse(fs.readFileSync(path.resolve("templates/pipeline-defaults.json"), "utf8")).rendering.uploadScale as number;
}

/**
 * Called by the renderer after final.mp4 is written. `renderInputHash` is the hash of the bytes the
 * render actually read, not of the file now on disk, which another assemble may have rewritten since.
 */
export function writeRenderStamp(slug: string, renderInputHash: string): void {
  const p = publishPaths(slug);
  fs.writeFileSync(p.renderStamp, JSON.stringify({ renderInput: renderInputHash, scale: uploadScale(), video: sha(p.video), renderedAt: new Date().toISOString() }, null, 2) + "\n");
}

/** Whether final.mp4 was rendered from the current render-input.json and is the file the stamp describes. */
export function renderIsCurrent(slug: string): { ok: boolean; why: string } {
  const p = publishPaths(slug);
  if (!fs.existsSync(p.video)) return { ok: false, why: `production/output/final.mp4 missing (npm run render -- ${slug})` };
  if (!fs.existsSync(p.renderStamp)) return { ok: false, why: "final.mp4 has no render stamp (rendered before stamps existed); re-render" };
  const s = JSON.parse(fs.readFileSync(p.renderStamp, "utf8"));
  if (s.video !== sha(p.video)) return { ok: false, why: "final.mp4 changed after its render" };
  if (s.renderInput !== sha(paths(slug).renderInput)) return { ok: false, why: "render-input.json changed since final.mp4 was rendered; re-render" };
  if (s.scale !== uploadScale()) return { ok: false, why: `final.mp4 was rendered at scale ${s.scale ?? 1}, upload scale is now ${uploadScale()}; re-render` };
  return { ok: true, why: `rendered ${s.renderedAt}` };
}
