import type { ColorPreset, VibePreset } from './types';

// ═══════════════════════════════════════════════════════════════════════════════
// COLOR PRESETS — 16 palettes, dark & light
// ═══════════════════════════════════════════════════════════════════════════════

export const colorPresets: ColorPreset[] = [
  // ── Dark Palettes ──────────────────────────────────────────────────────
  {
    id: 'dusty-rose',
    name: 'Muted Documentary',
    description: 'Muted pink/blue on deep dark base. Professional, analytic, documentary.',
    mode: 'dark',
    colors: {
      bgTop: '#1A1B22',
      bgBottom: '#1A1B22',
      accent1: '#D8A7B1',
      accent2: '#90AFC5',
      text: '#EAE0D5',
      textMuted: 'rgba(234, 224, 213, 0.6)',
      positive: '#5BBF8C',
      negative: '#E06070',
      surface: 'rgba(255, 255, 255, 0.06)',
      border: 'rgba(234, 224, 213, 0.12)',
    },
  },
  {
    id: 'electric-neon',
    name: 'Electric Neon',
    description: 'Cyan/coral neon on near-black. Cyberpunk energy.',
    mode: 'dark',
    colors: {
      bgTop: '#0A0A14',
      bgBottom: '#12121F',
      accent1: '#00F5D4',
      accent2: '#FE6D73',
      text: '#FFFFFF',
      textMuted: 'rgba(255, 255, 255, 0.5)',
      positive: '#00F5D4',
      negative: '#FE6D73',
      surface: 'rgba(255, 255, 255, 0.04)',
      border: 'rgba(255, 255, 255, 0.08)',
    },
  },
  {
    id: 'gold-navy',
    name: 'Gold & Navy',
    description: 'Yellow/blue data pair on dark slate. Bold, utilitarian.',
    mode: 'dark',
    colors: {
      bgTop: '#111827',
      bgBottom: '#1F2937',
      accent1: '#FBBF24',
      accent2: '#60A5FA',
      text: '#F9FAFB',
      textMuted: 'rgba(249, 250, 251, 0.5)',
      positive: '#34D399',
      negative: '#F87171',
      surface: 'rgba(255, 255, 255, 0.05)',
      border: 'rgba(255, 255, 255, 0.1)',
    },
  },
  {
    id: 'deep-purple',
    name: 'Deep Purple',
    description: 'Purple/cyan on cosmic navy. Glassmorphic, layered.',
    mode: 'dark',
    colors: {
      bgTop: '#0F0F23',
      bgBottom: '#1A1A3E',
      accent1: '#A78BFA',
      accent2: '#67E8F9',
      text: '#F0F0FF',
      textMuted: 'rgba(240, 240, 255, 0.5)',
      positive: '#6EE7B7',
      negative: '#FCA5A5',
      surface: 'rgba(255, 255, 255, 0.08)',
      border: 'rgba(255, 255, 255, 0.15)',
    },
  },
  {
    id: 'warm-stone',
    name: 'Warm Stone',
    description: 'Orange/sky on stone-dark. Warm, inviting, minimal.',
    mode: 'dark',
    colors: {
      bgTop: '#1C1917',
      bgBottom: '#292524',
      accent1: '#FB923C',
      accent2: '#38BDF8',
      text: '#FAFAF9',
      textMuted: 'rgba(250, 250, 249, 0.5)',
      positive: '#4ADE80',
      negative: '#FB7185',
      surface: 'rgba(255, 255, 255, 0.04)',
      border: 'rgba(255, 255, 255, 0.06)',
    },
  },
  {
    id: 'emerald-night',
    name: 'Emerald Night',
    description: 'Green/amber on dark forest. Nature, growth, wealth.',
    mode: 'dark',
    colors: {
      bgTop: '#0C1A14',
      bgBottom: '#162B22',
      accent1: '#10B981',
      accent2: '#F59E0B',
      text: '#ECFDF5',
      textMuted: 'rgba(236, 253, 245, 0.5)',
      positive: '#34D399',
      negative: '#EF4444',
      surface: 'rgba(255, 255, 255, 0.05)',
      border: 'rgba(255, 255, 255, 0.08)',
    },
  },
  {
    id: 'crimson-slate',
    name: 'Crimson Slate',
    description: 'Red/steel on charcoal. Serious, urgent, newsroom.',
    mode: 'dark',
    colors: {
      bgTop: '#18181B',
      bgBottom: '#27272A',
      accent1: '#EF4444',
      accent2: '#94A3B8',
      text: '#FAFAFA',
      textMuted: 'rgba(250, 250, 250, 0.5)',
      positive: '#22C55E',
      negative: '#EF4444',
      surface: 'rgba(255, 255, 255, 0.05)',
      border: 'rgba(255, 255, 255, 0.1)',
    },
  },
  {
    id: 'ocean-depth',
    name: 'Ocean Depth',
    description: 'Teal/coral on deep ocean blue. Calm yet vivid.',
    mode: 'dark',
    colors: {
      bgTop: '#0A1628',
      bgBottom: '#0F2440',
      accent1: '#2DD4BF',
      accent2: '#FB7185',
      text: '#F0F9FF',
      textMuted: 'rgba(240, 249, 255, 0.5)',
      positive: '#4ADE80',
      negative: '#F87171',
      surface: 'rgba(255, 255, 255, 0.06)',
      border: 'rgba(255, 255, 255, 0.1)',
    },
  },
  {
    id: 'midnight-ink',
    name: 'Midnight Ink',
    description: 'Monochrome with blue tint. Sleek, professional, premium.',
    mode: 'dark',
    colors: {
      bgTop: '#0B0F19',
      bgBottom: '#141B2D',
      accent1: '#E2E8F0',
      accent2: '#64748B',
      text: '#F8FAFC',
      textMuted: 'rgba(248, 250, 252, 0.4)',
      positive: '#4ADE80',
      negative: '#F87171',
      surface: 'rgba(255, 255, 255, 0.04)',
      border: 'rgba(255, 255, 255, 0.08)',
    },
  },
  {
    id: 'sunset-blaze',
    name: 'Sunset Blaze',
    description: 'Orange-red gradient on warm dark. Energetic, passionate.',
    mode: 'dark',
    colors: {
      bgTop: '#1A0F0A',
      bgBottom: '#2D1810',
      accent1: '#F97316',
      accent2: '#E879F9',
      text: '#FFF7ED',
      textMuted: 'rgba(255, 247, 237, 0.5)',
      positive: '#4ADE80',
      negative: '#FB7185',
      surface: 'rgba(255, 255, 255, 0.05)',
      border: 'rgba(255, 255, 255, 0.08)',
    },
  },

  // ── Light Palettes ─────────────────────────────────────────────────────
  {
    id: 'warm-editorial',
    name: 'Warm Editorial',
    description: 'Terracotta/teal on warm paper. Print-inspired.',
    mode: 'light',
    colors: {
      bgTop: '#F5F0EB',
      bgBottom: '#EDE7E0',
      accent1: '#C45D3E',
      accent2: '#2B6B8A',
      text: '#1A1A1A',
      textMuted: 'rgba(26, 26, 26, 0.55)',
      positive: '#3D8B5F',
      negative: '#C45D3E',
      surface: 'rgba(0, 0, 0, 0.03)',
      border: 'rgba(0, 0, 0, 0.08)',
    },
  },
  {
    id: 'clean-white',
    name: 'Clean White',
    description: 'Blue/indigo on pure white. Corporate, trustworthy.',
    mode: 'light',
    colors: {
      bgTop: '#FFFFFF',
      bgBottom: '#F8FAFC',
      accent1: '#3B82F6',
      accent2: '#8B5CF6',
      text: '#0F172A',
      textMuted: 'rgba(15, 23, 42, 0.5)',
      positive: '#22C55E',
      negative: '#EF4444',
      surface: 'rgba(0, 0, 0, 0.02)',
      border: 'rgba(0, 0, 0, 0.06)',
    },
  },
  {
    id: 'sage-cream',
    name: 'Sage & Cream',
    description: 'Green/brown on cream. Organic, calm, educational.',
    mode: 'light',
    colors: {
      bgTop: '#FEFCE8',
      bgBottom: '#FEF9C3',
      accent1: '#65A30D',
      accent2: '#92400E',
      text: '#1C1917',
      textMuted: 'rgba(28, 25, 23, 0.5)',
      positive: '#16A34A',
      negative: '#DC2626',
      surface: 'rgba(0, 0, 0, 0.03)',
      border: 'rgba(0, 0, 0, 0.08)',
    },
  },
  {
    id: 'blush-ink',
    name: 'Blush & Ink',
    description: 'Rose/dark blue on soft pink. Elegant, feminine, modern.',
    mode: 'light',
    colors: {
      bgTop: '#FFF1F2',
      bgBottom: '#FFE4E6',
      accent1: '#E11D48',
      accent2: '#1E3A5F',
      text: '#1C1917',
      textMuted: 'rgba(28, 25, 23, 0.5)',
      positive: '#059669',
      negative: '#E11D48',
      surface: 'rgba(0, 0, 0, 0.02)',
      border: 'rgba(0, 0, 0, 0.06)',
    },
  },
  {
    id: 'arctic-frost',
    name: 'Arctic Frost',
    description: 'Ice blue/slate on cool gray. Technical, precise, cold.',
    mode: 'light',
    colors: {
      bgTop: '#F0F4F8',
      bgBottom: '#E2E8F0',
      accent1: '#0EA5E9',
      accent2: '#475569',
      text: '#0F172A',
      textMuted: 'rgba(15, 23, 42, 0.5)',
      positive: '#10B981',
      negative: '#F43F5E',
      surface: 'rgba(0, 0, 0, 0.02)',
      border: 'rgba(0, 0, 0, 0.06)',
    },
  },
  {
    id: 'newspaper',
    name: 'Newspaper',
    description: 'Black/red on off-white. Classic print, high contrast.',
    mode: 'light',
    colors: {
      bgTop: '#FAF9F6',
      bgBottom: '#F5F3EE',
      accent1: '#1A1A1A',
      accent2: '#B91C1C',
      text: '#111111',
      textMuted: 'rgba(17, 17, 17, 0.5)',
      positive: '#15803D',
      negative: '#B91C1C',
      surface: 'rgba(0, 0, 0, 0.03)',
      border: 'rgba(0, 0, 0, 0.12)',
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// VIBE PRESETS — 6 approach/mood presets (no colors)
// ═══════════════════════════════════════════════════════════════════════════════

export const vibePresets: VibePreset[] = [
  {
    id: 'cinematic',
    name: 'Cinematic',
    description: 'Slow, editorial, spacious. Documentary/Vox feel.',
    typography: {
      fontFamily: 'Playfair Display, serif',
      headingWeight: 700,
      bodyWeight: 400,
      monoFont: 'IBM Plex Mono, monospace',
    },
    geometry: {
      cornerRadius: 2,
      borderWidth: 1,
      screenUtilization: 0.7,
      asymmetry: 0.15,
      alignment: 'center',
    },
    effects: {
      glassOpacity: 0,
      glowIntensity: 0,
      shadowDepth: 'whisper',
      gradientAngle: 180,
    },
    animation: {
      speed: 'slow',
      springDamping: 22,
      springStiffness: 50,
      stagger: 140,
    },
  },
  {
    id: 'dashboard',
    name: 'Data Dashboard',
    description: 'Tight, dense, fast. Visual Capitalist/Fireship feel.',
    typography: {
      fontFamily: 'Red Hat Display, sans-serif',
      headingWeight: 900,
      bodyWeight: 400,
      monoFont: 'Source Code Pro, monospace',
    },
    geometry: {
      cornerRadius: 6,
      borderWidth: 2,
      screenUtilization: 0.92,
      asymmetry: 0.35,
      alignment: 'left',
    },
    effects: {
      glassOpacity: 0.04,
      glowIntensity: 0.1,
      shadowDepth: 'soft',
      gradientAngle: 170,
    },
    animation: {
      speed: 'fast',
      springDamping: 12,
      springStiffness: 100,
      stagger: 50,
    },
  },
  {
    id: 'explainer',
    name: 'Explainer',
    description: 'Friendly, rounded, moderate. Kurzgesagt/educational feel.',
    typography: {
      fontFamily: 'Nunito Sans, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      monoFont: 'Space Mono, monospace',
    },
    geometry: {
      cornerRadius: 14,
      borderWidth: 0,
      screenUtilization: 0.8,
      asymmetry: 0.1,
      alignment: 'center',
    },
    effects: {
      glassOpacity: 0.06,
      glowIntensity: 0.15,
      shadowDepth: 'soft',
      gradientAngle: 180,
    },
    animation: {
      speed: 'normal',
      springDamping: 14,
      springStiffness: 80,
      stagger: 90,
    },
  },
  {
    id: 'breaking',
    name: 'Breaking News',
    description: 'Bold, condensed, high contrast, urgent pace.',
    typography: {
      fontFamily: 'Bebas Neue, sans-serif',
      headingWeight: 400, // Bebas only has 400
      bodyWeight: 400,
      monoFont: 'JetBrains Mono, monospace',
    },
    geometry: {
      cornerRadius: 0,
      borderWidth: 3,
      screenUtilization: 0.95,
      asymmetry: 0.5,
      alignment: 'left',
    },
    effects: {
      glassOpacity: 0,
      glowIntensity: 0.4,
      shadowDepth: 'none',
      gradientAngle: 160,
    },
    animation: {
      speed: 'fast',
      springDamping: 10,
      springStiffness: 120,
      stagger: 40,
    },
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Maximum whitespace, thin lines, zen-like calm.',
    typography: {
      fontFamily: 'Outfit, sans-serif',
      headingWeight: 500,
      bodyWeight: 300,
      monoFont: 'Fira Mono, monospace',
    },
    geometry: {
      cornerRadius: 8,
      borderWidth: 0,
      screenUtilization: 0.6,
      asymmetry: 0,
      alignment: 'center',
    },
    effects: {
      glassOpacity: 0,
      glowIntensity: 0,
      shadowDepth: 'none',
      gradientAngle: 180,
    },
    animation: {
      speed: 'slow',
      springDamping: 24,
      springStiffness: 40,
      stagger: 120,
    },
  },
  {
    id: 'retro',
    name: 'Retro Analog',
    description: 'Serif + mono, grain texture feel, warm nostalgia.',
    typography: {
      fontFamily: 'Fraunces, serif',
      headingWeight: 900,
      bodyWeight: 400,
      monoFont: 'Space Mono, monospace',
    },
    geometry: {
      cornerRadius: 4,
      borderWidth: 2,
      screenUtilization: 0.78,
      asymmetry: 0.25,
      alignment: 'left',
    },
    effects: {
      glassOpacity: 0,
      glowIntensity: 0,
      shadowDepth: 'soft',
      gradientAngle: 175,
    },
    animation: {
      speed: 'normal',
      springDamping: 18,
      springStiffness: 65,
      stagger: 100,
    },
  },
];

// ─── Defaults ───────────────────────────────────────────────────────────────

export const defaultColorPreset = colorPresets[0]; // Dusty Rose
export const defaultVibePreset = vibePresets[2]; // Explainer
