// Design System Tool — Export Utilities
// Generates design-system.json (machine-readable) and DESIGN.md (AI-agent-readable)

import type { DesignSystem, DesignSystemExport } from '../types';

/**
 * Build the JSON export payload
 */
export function buildJsonExport(
  system: DesignSystem,
  channelSlug?: string,
): DesignSystemExport {
  return {
    ...system,
    exportedAt: new Date().toISOString(),
    exportedFrom: 'design-system-tool',
    channelSlug,
  };
}

/**
 * Build DESIGN.md — a semantic, AI-agent-readable description of the design system.
 * Inspired by Stitch's design-md skill: descriptive color names + hex + functional role.
 */
export function buildDesignMd(system: DesignSystem): string {
  const { colors, typography, geometry, effects, animation } = system;

  const shadowLabel = {
    none: 'No shadows — completely flat surfaces',
    whisper: 'Barely perceptible shadows — subtle depth',
    soft: 'Soft diffused shadows — moderate depth',
    floating: 'Deep shadows — elements feel elevated',
  }[effects.shadowDepth];

  const speedLabel = {
    slow: 'Slow, cinematic transitions (~800ms)',
    normal: 'Standard, fluid transitions (~500ms)',
    fast: 'Snappy, energetic transitions (~300ms)',
  }[animation.speed];

  const alignLabel = {
    center: 'Centered — balanced, symmetrical layouts',
    left: 'Left-aligned — editorial, scan-friendly',
    right: 'Right-aligned — unconventional, dramatic',
  }[geometry.alignment];

  const utilizationLabel =
    geometry.screenUtilization < 0.7
      ? 'Spacious — generous whitespace, breathing room'
      : geometry.screenUtilization < 0.85
        ? 'Balanced — moderate density, clear hierarchy'
        : 'Compact — high density, information-rich';

  const glassLabel =
    effects.glassOpacity < 0.2
      ? 'Nearly opaque surfaces'
      : effects.glassOpacity < 0.5
        ? 'Subtle translucency'
        : effects.glassOpacity < 0.8
          ? 'Glassmorphic — visible depth layers'
          : 'Full glass — maximum transparency';

  const glowLabel =
    effects.glowIntensity < 0.2
      ? 'No glow — flat lighting'
      : effects.glowIntensity < 0.5
        ? 'Subtle glow — gentle accent highlights'
        : effects.glowIntensity < 0.8
          ? 'Moderate glow — noticeable light bleed'
          : 'Strong glow — neon-like luminance';

  return `# Design System — ${system.name}
> Version ${system.version} | Generated by design-system-tool

${system.promptInput ? `## Design Intent\n${system.promptInput}\n` : ''}
## Color Palette

| Role | Name | Value | Usage |
|------|------|-------|-------|
| Background Top | bgTop | \`${colors.bgTop}\` | Upper gradient stop for full-screen backgrounds |
| Background Bottom | bgBottom | \`${colors.bgBottom}\` | Lower gradient stop for full-screen backgrounds |
| Primary Accent | accent1 | \`${colors.accent1}\` | Headlines, progress bars, primary data series, CTAs |
| Secondary Accent | accent2 | \`${colors.accent2}\` | Comparison data, secondary highlights, contrast pairs |
| Body Text | text | \`${colors.text}\` | Primary readable text on dark backgrounds |
| Muted Text | textMuted | \`${colors.textMuted}\` | Captions, labels, de-emphasized information |
| Positive | positive | \`${colors.positive}\` | Growth indicators, success states, upward trends |
| Negative | negative | \`${colors.negative}\` | Decline indicators, warnings, downward trends |
| Surface | surface | \`${colors.surface}\` | Card backgrounds, panels, elevated containers |
| Border | border | \`${colors.border}\` | Dividers, outlines, subtle boundaries |

### Contrast Pairs
- **Comparison:** accent1 (${colors.accent1}) vs accent2 (${colors.accent2}) — use for duel/comparison scenes
- **Sentiment:** positive (${colors.positive}) vs negative (${colors.negative}) — use for up/down, good/bad data
- **Hierarchy:** text (${colors.text}) over textMuted (${colors.textMuted}) — visual importance levels

## Typography

| Property | Value |
|----------|-------|
| Primary Font | ${typography.fontFamily} |
| Heading Weight | ${typography.headingWeight} |
| Body Weight | ${typography.bodyWeight} |
| Monospace Font | ${typography.monoFont} |

## Geometry & Layout

| Property | Value | Description |
|----------|-------|-------------|
| Corner Radius | ${geometry.cornerRadius}px | ${geometry.cornerRadius === 0 ? 'Sharp edges — technical, modern' : geometry.cornerRadius <= 6 ? 'Subtle rounding — clean, professional' : geometry.cornerRadius <= 12 ? 'Rounded — friendly, approachable' : 'Pill-shaped — playful, bold'} |
| Border Width | ${geometry.borderWidth}px | ${geometry.borderWidth === 0 ? 'No borders — shapes defined by color alone' : geometry.borderWidth === 1 ? 'Hairline borders — subtle definition' : 'Thick borders — strong structure'} |
| Screen Utilization | ${Math.round(geometry.screenUtilization * 100)}% | ${utilizationLabel} |
| Asymmetry | ${Math.round(geometry.asymmetry * 100)}% | ${geometry.asymmetry < 0.3 ? 'Symmetric — balanced, formal' : geometry.asymmetry < 0.7 ? 'Mixed — some asymmetric elements' : 'Asymmetric — dynamic, editorial'} |
| Alignment | ${geometry.alignment} | ${alignLabel} |

## Effects

| Property | Value | Description |
|----------|-------|-------------|
| Glass Opacity | ${Math.round(effects.glassOpacity * 100)}% | ${glassLabel} |
| Glow Intensity | ${Math.round(effects.glowIntensity * 100)}% | ${glowLabel} |
| Shadow Depth | ${effects.shadowDepth} | ${shadowLabel} |
| Gradient Angle | ${effects.gradientAngle}deg | Background gradient direction |

## Animation

| Property | Value | Description |
|----------|-------|-------------|
| Speed | ${animation.speed} | ${speedLabel} |
| Spring Damping | ${animation.springDamping} | ${animation.springDamping < 10 ? 'Bouncy — playful oscillation' : animation.springDamping < 20 ? 'Balanced — natural settle' : 'Overdamped — smooth, no bounce'} |
| Spring Stiffness | ${animation.springStiffness} | ${animation.springStiffness < 100 ? 'Gentle — slow spring response' : animation.springStiffness < 200 ? 'Standard — natural feel' : 'Tight — quick, responsive'} |
| Stagger | ${animation.stagger}ms | Delay between sequential element animations |

## Agent Instructions

When creating video scenes with this design system:

1. **Always use the exact hex values** from the color palette above — never improvise colors.
2. **Respect contrast pairs** — comparisons use accent1 vs accent2, sentiment uses positive vs negative.
3. **Corner radius is ${geometry.cornerRadius}px** for all rounded elements (cards, charts, buttons).
4. **Screen utilization is ${Math.round(geometry.screenUtilization * 100)}%** — ${geometry.screenUtilization < 0.7 ? 'leave generous margins' : geometry.screenUtilization < 0.85 ? 'use moderate margins' : 'use tight margins, maximize content area'}.
5. **Shadow depth is "${effects.shadowDepth}"** — ${effects.shadowDepth === 'none' ? 'do not add box shadows' : 'apply consistent shadow depth to elevated elements'}.
6. **Glass effects at ${Math.round(effects.glassOpacity * 100)}%** — ${effects.glassOpacity < 0.3 ? 'surfaces should be mostly opaque' : 'add backdrop blur and transparency to surface elements'}.
7. **Animation speed is "${animation.speed}"** — ${speedLabel.toLowerCase()}.
`;
}

/**
 * Trigger browser download of a text file
 */
export function downloadFile(
  content: string,
  filename: string,
  mimeType = 'text/plain',
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export both files (JSON + DESIGN.md) via browser downloads
 */
export function exportDesignSystem(
  system: DesignSystem,
  channelSlug?: string,
): void {
  const jsonPayload = buildJsonExport(system, channelSlug);
  downloadFile(
    JSON.stringify(jsonPayload, null, 2),
    'design-system.json',
    'application/json',
  );

  const markdown = buildDesignMd(system);
  downloadFile(markdown, 'DESIGN.md', 'text/markdown');
}
